name: retroshare
description: Retroshare mobile client

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  qr_flutter: ^4.0.0
  qrscan: ^0.3.2
  tuple: ^1.0.2
  flutter_redux: ^0.8.2
  image_picker: ^0.6.6+4
  sliding_up_panel: ^0.3.4
  # Toast
  oktoast: ^2.1.8
  flutter_spinkit: "^4.1.2"
  image_gallery_saver: ^1.6.9
  #emoji_picker: ^0.0.3
  transparent_image: ^1.0.0
  cached_network_image: ^2.4.1
  flutter_image_compress: ^0.7.0

  # https://gitlab.com/b1rdG/retroshare-dart-see
  eventsource:
    path: "../retroshare-dart-see"

  # https://gitlab.com/jpascualsana/openapi-dart-retroshare-api-wrapper
  openapi:
    path: "../openapi-dart-retroshare-api-wrapper"

  # Used to render chat messages
  flutter_html: ^0.11.1

  # For notifications
  flutter_local_notifications: ^1.4.3
  rxdart: ^0.23.1
  html: ^0.14.0+3
  provider: ^5.0.0
  path_provider: ^2.0.2
  flutter_custom_dialog: ^1.0.20
  fluttertoast: ^8.0.7
  webview_flutter: ^1.0.7
  # Share RetroShare Invite
  share: ^2.0.4
  #shared_preferences: ^0.5.4+1
  google_fonts: ^1.1.0
  font_awesome_flutter: ">= 4.7.0"
  step_progress_indicator: ^1.0.1
  liquid_progress_indicator: ^0.4.0
  cool_alert: ^1.1.0
  shimmer: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/rs-logo.png
    - assets/icons8/pluto-fatal-error.png
    - assets/icons8/pluto-no-messages-1.png
    - assets/icons8/pluto-sign-in.png
    - assets/icons8/list-is-empty-3.png
    - assets/icons8/pluto-children-parent-relationships-petting-animal.png
    - assets/icons8/sport-yoga-reading-1.png
    - assets/icons8/virtual-reality.png
    - assets/icons8/participant_list.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Oxygen
      fonts:
        - asset: assets/fonts/Oxygen-Regular.ttf
        - asset: assets/fonts/Oxygen-Light.ttf
        - asset: assets/fonts/Oxygen-Bold.ttf

    - family: Abel
      fonts:
        - asset: assets/fonts/Abel-Regular.ttf
    - family: Vollkorn
      fonts:
        - asset: assets/fonts/Vollkorn/static/Vollkorn-Regular.ttf
        - asset: assets/fonts/Vollkorn/static/Vollkorn-Medium.ttf
          weight: 500
        - asset: assets/fonts/Vollkorn/static/Vollkorn-Bold.ttf
          weight: 700
  #
  #
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
