name: retroshare
description: Retroshare mobile client

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1
  http: ^0.13.3
  qr_flutter: ^4.0.0
  tuple: ^2.0.0
  image_picker: ^1.0.7
  sliding_up_panel: ^2.0.0
  qrscan: ^0.3.1
  # Toast
  oktoast: ^3.0.0
  image_gallery_saver: ^2.0.3
  emoji_picker_flutter: ^1.0.6
  permission_handler: ^11.2.0

  # https://gitlab.com/jpascualsana/openapi-dart-retroshare-api-wrapper
  #retroshare_api_wrapper:
    #path: "../Retroshare-Wrapper"

  # https://github.com/Kumaravinash9/Retroshare-Wrapper
  retroshare_api_wrapper:
    git:
      url: 'https://github.com/ayushkoli772/Retroshare-Wrapper.git'
      ref: master

   


  # Used to render chat messages
  flutter_html: ^2.0.0
  flutter_chips_input: ^2.0.0
  # For notifications
  flutter_local_notifications: ^8.2.0
  rxdart: ^0.27.7
  html: ^0.15.0
  provider: ^6.1.1
  path_provider: ^2.0.2
  fluttertoast: ^8.0.8
  webview_flutter: ^2.0.0
  # Share RetroShare Invite
  share: ^2.0.4
  google_fonts: ^4.0.4
  font_awesome_flutter: '>= 4.7.0'
  cool_alert: ^2.0.1
  shimmer: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
 

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/rs-logo.png
    - assets/icons8/pluto-fatal-error.png
    - assets/icons8/pluto-no-messages-1.png
    - assets/icons8/pluto-sign-in.png
    - assets/icons8/list-is-empty-3.png
    - assets/icons8/pluto-children-parent-relationships-petting-animal.png
    - assets/icons8/sport-yoga-reading-1.png
    - assets/icons8/virtual-reality.png
    - assets/icons8/friends_together.png
    - assets/icons8/pluto_notification.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Oxygen
      fonts:
        - asset: assets/fonts/Oxygen-Regular.ttf
        - asset: assets/fonts/Oxygen-Light.ttf
        - asset: assets/fonts/Oxygen-Bold.ttf
         
    - family: Abel
      fonts:
        - asset: assets/fonts/Abel-Regular.ttf
    - family: Vollkorn
      fonts:
        - asset: assets/fonts/Vollkorn/static/Vollkorn-Regular.ttf
        - asset: assets/fonts/Vollkorn/static/Vollkorn-Medium.ttf
          weight: 500
        - asset: assets/fonts/Vollkorn/static/Vollkorn-Bold.ttf
          weight: 700
  #     
  #     
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
